---

language: bash

matrix:
  fast_finish: true

before_install:
  - >
    if [ -n "$TRAVIS_TAG" ]; then
      sudo apt-get install -y build-essential fakeroot debsigs;
      openssl aes-256-cbc -K $encrypted_741831696b91_key -iv $encrypted_741831696b91_iv -in dist/gpg_key.priv.enc -out dist/gpg_key.priv -d;
      gpg --import dist/gpg_key.priv;
    fi

script:
  - >
    if [ -n "$TRAVIS_TAG" ]; then
      dist/build.sh;
    fi

deploy:
  - provider: packagecloud
    username: prometheus-deb
    repository: release
    token:
      secure: TxXxAcHpUc9tonqDXed5cM4aMeYczgAN+4hILx22ht9/qZG7oPk9rVGiK1KnI1pFCunhqcHm9MNajrJzkWunK+Q8e+v39Whb7rJoSf9Mt2Ff5GHQ+NKDzwPF7N4P3lutTHVS08iUpDQjMsXBJh0s7VaiNafK+iQ3Q3TMUgl/bN+8+hC/R2hD8fPbtOFpChi1eH8iR6HfH6SRiAIgqUi9IlmpZ2JF7aBzd3I+RvQaZRc178mIee6OLU9YafxzNMrKdleHUlV0j5baemCc9GWsU827ki5txE62A2pwkccosRKwZ3xkTFnphZuHisvMAqvhZuPQCfIvJRfOKlAfj6r5QjBhHMuTLQLc5qYmJMFx1PjN5v6x+SzoxLIK7okiDb9BIBKYKySxbNoJPtqnLOjDslEAV/dG2P3dZRiMqUfM6+tblBGoVbJOHPTwhjqcd+Ot4HL00evB7deHXouzwpYxPKA4Op7n97UYEJ/CWUJdcUO4QnnrlT1WiH/1gH6z+9T4g5iqFb8hIuSREOChPxYG37RlAWhbGKNMdIPWaeg9ewX8+q5ytfCCn9sqKZrxkPVmZtmdWi4mf8toPwNRHdWUf0jYlxy05fUTkN9R8bxRyxUjqKD8r1JMrN/NeDoN4QmoRhkoTRD/IegBLAYQ5xHKTs0k5oQARWhpdRYuhZ2WVSw=
    dist: ubuntu/xenial
    skip_cleanup: true
    local-dir: /tmp/prometheus
    package_glob: "*.deb"
    on:
      tags: true
      repo: jtyr/prometheus-deb

notifications:
  email: false
